### ISSUE TITLE
FEATURE: Make provisioning Tanzu SQL Postgres instance as TAP GUI back-end the default

### ISSUE THREAD

**Issue by pacphi** [pacphi/gha-workflows-with-gitops-for-tanzu-application-platform#4]
We already have this conditional config in `full` and `view` profile tap-values config

```
    backend:
      baseUrl: #@ "https://{}".format(data.values.tap.domains.tapGui)
      cors:
        origin: #@ "https://{}".format(data.values.tap.domains.tapGui)
      #@ if "backstage" in data.values.tap.credentials and "database" in data.values.tap.credentials.backstage:
      backend:
        database:
          client: #@ data.values.tap.credentials.backstage.database.client
          connection:
            host: #@ data.values.tap.credentials.backstage.database.host
            port: #@ data.values.tap.credentials.backstage.database.port
            user: #@ data.values.tap.credentials.backstage.database.username
            password: #@ data.values.tap.credentials.backstage.database.password
            ssl: {rejectUnauthorized: true}
      #@ end
```

We should create self-service dispatch and supporting call Github Action workflows to provision a Tanzu SQL Postgres instance, then retrieve connection credentials, and add them (i.e., plumb them in) to config, before initiating TAP install.
